ReallySimpleCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from contacts.views import LandingPageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('contacts/', include('contacts.urls', namespace="contacts")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contacts/urls.py
from django.urls import path
from .views import ContactListView, ContactDetailView, ContactCreateView, ContactUpdateView, ContactDeleteView, export_contacts_xls, import_contacts_xls

app_name = "contacts"

urlpatterns = [
  path('', ContactListView.as_view(), name="contact-list"),
  path('create/', ContactCreateView.as_view(), name="contact-create"),
  path('<int:pk>/', ContactDetailView.as_view(), name="contact-detail"),
  path('<int:pk>/update/', ContactUpdateView.as_view(), name="contact-update"),
  path('<int:pk>/delete/', ContactDeleteView.as_view(), name="contact-delete"),
  path('export/excel/', export_contacts_xls, name='contact-export'),
  path('import/excel/', import_contacts_xls, name='contact-import')
]

contacts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
  pass
  #creating own User model (inheriting AbstractUser model) to have more flexibility to add customized fields as needed.

class Contact(models.Model):
  first_name = models.CharField(max_length=20)
  last_name = models.CharField(max_length=20)
  email = models.EmailField(blank=True, null=True, max_length=254)
  address_1 = models.CharField(blank=True, null=True, max_length=20)
  address_2 = models.CharField(blank=True, null=True, max_length=20)
  city = models.CharField(blank=True, null=True, max_length=20)
  state = models.CharField(blank=True, null=True, max_length=20)
  zipcode = models.CharField(blank=True, null=True, max_length=5)
  profile_photo = models.ImageField(default='static/images/default-profile-photo.jpeg', upload_to='static/images/', blank=True, null=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)
  #foreign key requires on_delete in case relational table is deleted. setting it to cascade to ensure contact list that is associated with a specific user is deleted if user profile no longer exist. can be set to null if contact list needs to exist regardless.

  def __str__(self):
    return f"{self.first_name} {self.last_name}"

contacts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model
from .models import Contact

User = get_user_model()

class ContactModelForm(forms.ModelForm):
  class Meta:
    model = Contact
    fields = (
        'first_name',
        'last_name',
        'email',
        'address_1',
        'address_2',
        'city',
        'state',
        'zipcode',
        'profile_photo',
    )


class ContactForm(forms.Form):
  first_name = forms.CharField(max_length=20)
  last_name = forms.CharField(max_length=20)
  email = forms.EmailField(required=False, max_length=254)
  address_1 = forms.CharField(required=False, max_length=20)
  address_2 = forms.CharField(required=False, max_length=20)
  city = forms.CharField(required=False, max_length=20)
  state = forms.CharField(required=False, max_length=20)
  zipcode = forms.IntegerField(required=False)
  profile_photo = forms.ImageField(required=False)


class CustomUserCreationForm(UserCreationForm):
  class Meta:
    model = User
    fields = ('username',)
    field_classes = {'username': UsernameField}

contacts/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Contact, User
from .forms import ContactForm, ContactModelForm, CustomUserCreationForm
import xlwt
import openpyxl

class SignupView(generic.CreateView):
  template_name = "registration/signup.html"
  form_class = CustomUserCreationForm
  def get_success_url(self):
    return reverse("login")

class LandingPageView(generic.TemplateView):
  template_name = "landing_page.html"

class ContactListView(LoginRequiredMixin, generic.ListView):
  template_name = "contact_list.html"
  context_object_name = 'contacts'

  def get_queryset(self):
    queryset = Contact.objects.all()
    if self.request.user.is_authenticated:
      queryset = queryset.filter(user=self.request.user)
    return queryset

class ContactDetailView(LoginRequiredMixin, generic.DetailView):
  template_name = "contact_detail.html"
  context_object_name = 'contact'

  def get_queryset(self):
    queryset = Contact.objects.all()
    if self.request.user.is_authenticated:
      queryset = queryset.filter(user=self.request.user)
    return queryset

class ContactCreateView(LoginRequiredMixin, generic.CreateView):
  template_name = "contact_create.html"
  form_class = ContactModelForm

  def get_success_url(self):
    return reverse("contacts:contact-list")

  def form_valid(self, form):
    contact = form.save(commit=False)
    contact.user = self.request.user
    contact.save()
    return super(ContactCreateView, self).form_valid(form)

class ContactUpdateView(LoginRequiredMixin, generic.UpdateView):
  template_name = "contact_update.html"
  form_class = ContactModelForm

  def get_queryset(self):
    queryset = Contact.objects.all()
    if self.request.user.is_authenticated:
      queryset = queryset.filter(user=self.request.user)
    return queryset

  def get_success_url(self):
    return reverse("contacts:contact-list")

class ContactDeleteView(LoginRequiredMixin, generic.DeleteView):
  template_name = "contact_delete.html"
  form_class = ContactModelForm

  def get_queryset(self):
    queryset = Contact.objects.all()
    if self.request.user.is_authenticated:
      queryset = queryset.filter(user=self.request.user)
    return queryset

  def get_success_url(self):
    return reverse("contacts:contact-list")

def export_contacts_xls(request):
  response = HttpResponse(content_type='application/ms-excel')
  response['Content-Disposition'] = 'attachment; filename="users.xls"'

  wb = xlwt.Workbook(encoding='utf-8')
  ws = wb.add_sheet("Contact List")

  row_num = 0
  font_style = xlwt.XFStyle()
  font_style.font.bold = True

  columns = ['first_name', 'last_name', 'email', 'address_1', 'address_2', 'city', 'state', 'zipcode', 'profile_photo', 'user']

  for col_num in range(len(columns)):
    ws.write(row_num, col_num, columns[col_num], font_style)

  font_style = xlwt.XFStyle()

  rows = Contact.objects.filter(user=request.user).values_list('first_name', 'last_name', 'email', 'address_1', 'address_2', 'city', 'state', 'zipcode', 'profile_photo', 'user')

  for row in rows:
    row_num += 1
    for col_num in range(len(row)):
      ws.write(row_num, col_num, row[col_num], font_style)

  wb.save(response)
  return response

# step 1 - create a view to handle uploading xls file
# step 2 - load xls file with openpyxl
# step 3 - seed db with xls data
# step 4 - render updated contact list on html

def import_contacts_xls(request):
  if request.method == "GET":
    return render(request, 'contact_upload.html', {})
  else:
    excel_file = request.FILES['excel_file']

    wb = openpyxl.load_workbook(excel_file)
    active_sheet = wb.active

    current_user = request.user
    columnTitles = {}
    current = 0

    for column in active_sheet.iter_cols(1, active_sheet.max_column):
      columnTitles[column[0].value] = current
      current += 1

    for row in active_sheet.iter_rows(min_row=2, values_only=True):
      Contact.objects.create(user=current_user, first_name=row[columnTitles['first_name']], last_name=row[columnTitles['last_name']], email=row[columnTitles['email']], address_1=row[columnTitles['address_1']], address_2=row[columnTitles['address_2']], city=row[columnTitles['city']], state=row[columnTitles['state']], zipcode=row[columnTitles['zipcode']])

    response = 'Upload Successful!'

  return render(request, 'contact_upload.html', {'success':response})

templates/contact_create.html
{% extends "main.html"%} {% block content %}

<h1>Really Simple CRM</h1>
<h4>New Contact</h4>
<br />
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }} {% comment %} csrf token always required
  whenever post method is called on forms {% endcomment %}
  <button type="submit">Submit</button>
</form>
<a href="{% url 'contacts:contact-list' %}">Back To Contact List</a>

{% endblock content%}

templates/contact_delete.html
{% extends "main.html"%} {% block content %}

<h1>Contact Delete</h1>

<h5>Are you sure you want to permanently delete this contact information?</h5>
<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <button type="submit" class="btn btn-primary">Confirm</button>
</form>

<a href="{% url 'contacts:contact-detail' contact.pk %}"
  >Back To Contact Detail</a
>
{% endblock content%}

templates/contact_detail.html
{% extends "main.html"%} {% block content %}

<h4>Contact Detail</h4>
<div class="card" style="width: 18rem;">
        <img
        src="{{ contact.profile_photo.url }}"
        class="card-img-top"
        alt="profile-photo"
        style="width: 100%"
      />
  <div class="card-body">
    <h5 class="card-title">{{ contact.first_name }} {{ contact.last_name }}</h5>
    <p class="card-text"><div>Email: {{ contact.email }}</div>
    <div>Address: {{ contact.address_1 }}</div>
    <div>Address: {{ contact.address_2 }}</div>
    <div>City: {{ contact.city }}</div>
    <div>State: {{ contact.state }}</div>
    <div>Zip: {{ contact.zipcode }}</div>
    <div>Manager: {{ contact.user }}</div>
</p>

    <a href="{% url 'contacts:contact-update' contact.pk %}" class="btn btn-primary">Edit</a>
<a href="{% url 'contacts:contact-delete' contact.pk %}" class="btn btn-primary">Delete</a>
<br />

  </div>
</div>
<a href="{% url 'contacts:contact-list'%}">Back To Contact List</a>

{% endblock content%}

templates/contact_list.html
{% extends "main.html"%} {% block content %}
<div
  class="row w-full mb-6 py-6 flex justify-between items-center border-b border-gray-2"
>
  <div>
    <h4>Contact List</h4>
  </div>
  <div>
    <a href="{% url 'contacts:contact-create' %}">New Contact</a>
  </div>
  <div>
    <a href="{% url 'contacts:contact-export'%}">Export</a><br />
    <a href="{% url 'contacts:contact-import'%}">Import</a>
  </div>
</div>
<div class="row row-cols-2 row-cols-md-3 g-2">
  {% for contact in contacts %}

  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">
          <a
            href="{% url 'contacts:contact-detail' contact.pk %}"
            style="font-size: 0.9rem"
          >
            <div>Name: {{ contact.first_name }} {{ contact.last_name }}</div>
            <div>Email: {{ contact.email }}</div>
          </a>
        </h5>
      </div>
    </div>
  </div>

  {% endfor %}
</div>
{% endblock content%}

templates/contact_update.html
{% extends "main.html"%} {% block content %}

<h1>Contact Update</h1>

<h5>{{ contact.first_name}} {{ contact.last_name}}</h5>
<form method="POST" class="row g-3" enctype="multipart/form-data">
  {% csrf_token %} {{form.as_p}}
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<a href="{% url 'contacts:contact-detail' contact.pk %}"
  >Back To Contact Detail</a
>
{% endblock content%}

templates/contact_upload.html
{% extends "main.html"%} {% block content %}

<h4>Import Contact</h4>
<br />

<form action="{% url "contacts:contact-import" %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<input type="file"
title="Upload excel file"
name="excel_file"
required="required">
<p>
<input type="submit"
value="Upload">
</form>

<hr>

<h4>{{ success }}</h4>

<br>
<a href="{% url 'contacts:contact-list' %}">Back To Contact List</a>

{% endblock content%}

templates/landing_page.html
{% extends "main.html" %} {% block content %}
<main>
  <div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">Really Simple CRM</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">
        Manage your contact list on our platform with built in features such as
        creating, listing, updating and deleting contact information.
      </p>
      {% if request.user.is_authenticated %}
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a
          class="btn btn-primary btn-lg px-4 gap-3"
          href="{% url 'contacts:contact-list' %}"
          >Open Contact List</a
        >
      </div>
      {% else %}
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
        <a class="btn btn-primary btn-lg px-4 gap-3" href="{% url 'signup' %}"
          >Sign Up</a
        >
        <a
          class="btn btn-outline-secondary btn-lg px-4"
          href="{% url 'login' %}"
          >Log In</a
        >
      </div>
      {% endif %}
    </div>
  </div>
</main>
{% endblock content %}

templates/main.html
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Really Simple CRM</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
  </head>
  <body>
    {% include 'navbar.html'%} {% block content %} {% endblock content%}
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'landing-page' %}"
      >Really Simple CRM</a
    >

    <ul class="nav justify-content-end">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <div class="nav-link mr-2">Logged in as: {{ user }}</div>
      </li>
      <li class="nav-item">
        <a class="nav-link active mr-2" href="{% url 'contacts:contact-list'%}"
          >Contacts</a
        >
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link active mr-2" href="{% url 'signup' %}">Sign Up</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>